#釣り場のテーブル更新時間(HH:mm:ss)
time: "00:00:00"

#テーブルのリストにregionが追加されます、ここからいろいろあーだのこーだのする
tableA:
  -
tableB:
  -
tableC:
  -
tableD:
  -
tableE:
  -
tableF:
  -
#テーブルごとにアイテムが設定されます
tableAItem:
  -
tableBItem:
  -
tableCItem:
  -
tableDItem:
  -
tableEItem:
  -
tableFItem:
  -
#隠し釣り場効果ごとのregion
doubleDrop:
  -
doubleTimes:
  -
upGraded:
  -


#隠し釣り場含む全region
regions:

#隠し釣り場
hidden_regions:

hologram:
  X: -381
  Y: 46
  Z: -668
hologramWorld: lobby
npcWorld: Main

#納品NPCリスト
npc:

#npcID
npcId:
  -
