name: SurvivalEvent
version: 1.1.6
main: xyz.masa3mc.survivalevent.SurvivalEvent
authors:
- Namekun
- uz_masa3
api-version: 1.19
softdepend:
- Citizens
- DecentHolograms
- NBTAPI
- WorldEdit
- WorldGuard
- WorldGuardEvents
commands:
  event:
    usage: /event
